<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-DGHGSVF1" ignored="0" name="model.CustomerTest" tests="27" failures="6" timestamp="25 Apr 2023 07:40:15 GMT" time="0.175" errors="0">
  <testcase name="testSetPassword on testSetPassword(model.CustomerTest)" time="0.002" classname="model.CustomerTest"/>
  <testcase name="testGetPassword on testGetPassword(model.CustomerTest)" time="0.001" classname="model.CustomerTest"/>
  <testcase name="testGetEmail on testGetEmail(model.CustomerTest)" time="0.001" classname="model.CustomerTest"/>
  <testcase name="testGetName1 on testGetName1(model.CustomerTest)" time="0.001" classname="model.CustomerTest"/>
  <testcase name="testGetName2 on testGetName2(model.CustomerTest)" time="0.003" classname="model.CustomerTest">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;&amp;gt; but was:&amp;lt;null&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<> but was:<null>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:120)
at org.junit.Assert.assertEquals(Assert.java:146)
at model.CustomerTest.testGetName2(CustomerTest.java:114)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testGetName2 on testGetName2(model.CustomerTest) -->
  <testcase name="testSetCard_id on testSetCard_id(model.CustomerTest)" time="0.006" classname="model.CustomerTest"/>
  <testcase name="testSetAddress1 on testSetAddress1(model.CustomerTest)" time="0.006" classname="model.CustomerTest"/>
  <testcase name="testSetAddress2 on testSetAddress2(model.CustomerTest)" time="0.006" classname="model.CustomerTest"/>
  <testcase name="testIsGender on testIsGender(model.CustomerTest)" time="0.013" classname="model.CustomerTest"/>
  <testcase name="testGetAddress1 on testGetAddress1(model.CustomerTest)" time="0.013" classname="model.CustomerTest"/>
  <testcase name="testGetAddress2 on testGetAddress2(model.CustomerTest)" time="0.013" classname="model.CustomerTest">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;&amp;gt; but was:&amp;lt;null&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<> but was:<null>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:120)
at org.junit.Assert.assertEquals(Assert.java:146)
at model.CustomerTest.testGetAddress2(CustomerTest.java:160)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testGetAddress2 on testGetAddress2(model.CustomerTest) -->
  <testcase name="testSetPhonenumber on testSetPhonenumber(model.CustomerTest)" time="0.014" classname="model.CustomerTest"/>
  <testcase name="testGetCard_id on testGetCard_id(model.CustomerTest)" time="0.014" classname="model.CustomerTest"/>
  <testcase name="testSetGender on testSetGender(model.CustomerTest)" time="0.014" classname="model.CustomerTest"/>
  <testcase name="testSetUsername on testSetUsername(model.CustomerTest)" time="0.014" classname="model.CustomerTest"/>
  <testcase name="testGetUsername on testGetUsername(model.CustomerTest)" time="0.015" classname="model.CustomerTest"/>
  <testcase name="testGetDob on testGetDob(model.CustomerTest)" time="0.051" classname="model.CustomerTest"/>
  <testcase name="testGetId1 on testGetId1(model.CustomerTest)" time="0.051" classname="model.CustomerTest"/>
  <testcase name="testGetId2 on testGetId2(model.CustomerTest)" time="0.051" classname="model.CustomerTest">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;-1&amp;gt; but was:&amp;lt;0&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<-1> but was:<0>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:633)
at model.CustomerTest.testGetId2(CustomerTest.java:59)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testGetId2 on testGetId2(model.CustomerTest) -->
  <testcase name="testSetDob on testSetDob(model.CustomerTest)" time="0.052" classname="model.CustomerTest">
    <failure type="org.junit.ComparisonFailure" message="expected:&amp;lt;[28/09/2001]&amp;gt; but was:&amp;lt;[]&amp;gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<[28/09/2001]> but was:<[]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at model.CustomerTest.testSetDob(CustomerTest.java:343)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testSetDob on testSetDob(model.CustomerTest) -->
  <testcase name="testSetId1 on testSetId1(model.CustomerTest)" time="0.105" classname="model.CustomerTest"/>
  <testcase name="testSetId2 on testSetId2(model.CustomerTest)" time="0.106" classname="model.CustomerTest">
    <failure type="java.lang.AssertionError" message="Expected exception: java.lang.Exception">
      <![CDATA[java.lang.AssertionError: Expected exception: java.lang.Exception
at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:34)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testSetId2 on testSetId2(model.CustomerTest) -->
  <testcase name="testSetId3 on testSetId3(model.CustomerTest)" time="0.106" classname="model.CustomerTest">
    <failure type="java.lang.AssertionError" message="Expected exception: java.lang.Exception">
      <![CDATA[java.lang.AssertionError: Expected exception: java.lang.Exception
at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:34)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testSetId3 on testSetId3(model.CustomerTest) -->
  <testcase name="testSetEmail on testSetEmail(model.CustomerTest)" time="0.171" classname="model.CustomerTest"/>
  <testcase name="testSetName1 on testSetName1(model.CustomerTest)" time="0.171" classname="model.CustomerTest"/>
  <testcase name="testSetName2 on testSetName2(model.CustomerTest)" time="0.171" classname="model.CustomerTest"/>
  <testcase name="testGetPhonenumber on testGetPhonenumber(model.CustomerTest)" time="0.171" classname="model.CustomerTest"/>
</testsuite> <!-- model.CustomerTest -->
